export const offense = [
  "Robbery",
  "Noise Disturbance",
  "Brawl / awayan",
  "Sexual Harrasment",
  "Missing Person/s",
  "Unpaid loans",
  "Concern",
  "Complaints",
  "Vandalism and Property Damage",
  "Suspicious Persons or Vehicles",
  "Burglary / Namasok Bahay",
  "Vehicle Collision",
  "Others",
];

export const bonuanArea = [
  "Calamiong",
  "Eastern County",
  "Las Vegas",
  "Maramba Banker's Village",
  "Perrenians",
  "Sabangan",
  "San Marino Place",
  "Alimango",
  "Alimasag",
  "Apahap",
  "Ayungin",
  "Bangus Avenue",
  "Baracuda",
  "Bisugo",
  "Bonito",
  "Dalagang Bukid",
  "Dasmarinas",
  "Don Marcelo I. Balolong Sr. Avenue",
  "Don Maximo",
  "Paras",
  "Sugpo",
  "Tanguegue",
  "Tondaligan",
  "Tuna",
];
