export const offense = [
  "Robbery",
  "Noise Disturbance",
  "Brawl / awayan",
  "Sexual Harrasment",
  "Missing Person/s",
  "Unpaid loans",
  "Concern",
  "Complaints",
  "Vandalism and Property Damage",
  "Suspicious Persons or Vehicles",
  "Burglary / Namasok Bahay",
  "Vehicle Collision",
  "Others",
];

export const bonuanArea = [
  "Alimango",
  "Alimasag",
  "Apahap",
  "Ayungin",
  "Bangus Avenue",
  "Baracuda",
  "Bisugo",
  "Bonito",
  "Calamiong",
  "Dalagang Bukid",
  "Dasmarinas",
  "Don Marcelo I. Balolong Sr. Avenue",
  "Don Maximo",
  "Eastern County",
  "Las Vegas",
  "Maramba Banker's Village",
  "Paras",
  "Perrenians",
  "Sabangan",
  "San Marino Place",
  "Sugpo",
  "Tanguegue",
  "Tondaligan",
  "Tuna",
];
